### ISSUE TITLE
poor Alpine performance

### ISSUE THREAD

**Issue by dotysan** [tianon/docker-bash#33]
Hi, I'm messing around with https://github.com/PlummersSoftwareLLC/Primes/blob/drag-race/PrimeBash/solution_1/Dockerfile and notice that if you change it to `FROM bash` instead of `FROM ubuntu` the performance is horrible.

This appears to be due to the Alpine distro. Any ideas why?

**Comment by yosifkit** [comment]
I don't think this is related to Alpine. I've run the prime scripts using bash from system packages in `alpine:3.17`, `ubuntu:devel`, and `debian:sid`; all give "Valid: False" on the first two tests (regular and inline). All three fail to even finish the "Packed" test in a reasonable time. I gave Alpine over 30 minutes while then testing out the others (since they only use a single core at most).  All three are using Bash `5.2.15`.  If I run using `bash:5.1` (version 5.1.16), then it produces "valid" results and the 3rd test finishes "quickly".

If you can figure where the bug or regression might be, I'm sure the upstream `bash` maintainer would be happy to have it.
